// GENERATED by scripts/build_sources.py — do not edit by hand.
//
// Resolved from vendor/wcc-gis/catalogue.json through the wcc_gis SDK. The
// adapters import from here so no upstream URL is ever written by hand.
// Regenerate with:  bun run sources:build

export const ENDPOINTS: Record<string, string> = {
  "metservice-alerts": "https://services.arcgis.com/XTtANUDT8Va4DLwI/arcgis/rest/services/Metservice_Weather_Alerts/FeatureServer/0",
  "nema-cap-alerts": "https://services5.arcgis.com/cJn6oR1QqErYBL5d/arcgis/rest/services/NZ_CAP_Alerts_(Read_only)/FeatureServer/0",
  "ema-rss": "https://alerthub.civildefence.govt.nz/rss/pwp",
  "wcc-road-closures": "https://gis.wcc.govt.nz/arcgis/rest/services/Transportation/StreetEventsAndRoadClosures/MapServer/1",
  "nzta-delays": "https://www.journeys.nzta.govt.nz/assets/map-data-cache/delays.json",
  "ww-faults": "https://services7.arcgis.com/2ECs938g489DMWjt/arcgis/rest/services/Job_Status_Public_View/FeatureServer/5",
  "electricity-outages": "https://services5.arcgis.com/cJn6oR1QqErYBL5d/arcgis/rest/services/electricity_outages_read_only/FeatureServer/0",
  "geonet-tilde-sea-level": "https://tilde.geonet.org.nz/v4/data/coastal/WLGT/water-height-detided/40/15s/nil/latest/6h",
  "baring-head-waves": "https://hilltop.gw.govt.nz/Data.hts",
  "hilltop-gauges": "https://hilltop.gw.govt.nz/Telemetry.hts",
  "open-meteo-marine": "https://marine-api.open-meteo.com/v1/marine",
  "open-meteo-forecast": "https://api.open-meteo.com/v1/forecast"
};

/** Wellington City bounding box (W, S, E, N) — from wcc_gis.WELLINGTON. */
export const WELLINGTON_BBOX: [number, number, number, number] = [174.62, -41.36, 174.94, -41.14];
