// GENERATED by scripts/build_suburbs.py — do not edit by hand.
//
// One entry per Wellington City suburb, derived from Council's own boundary
// polygons: `centre` is the shoelace centroid of the largest ring, `radiusM`
// is the radius of a circle of equal area, clamped to 800–4000 m.
//
// `centre` and `radiusM` are for DISTANCE only — how near a signal is to the
// area a resident chose. Whether a point is *in* a suburb is answered by the
// polygon in suburbs.generated.ts, never by this radius.
// Regenerate with:  bun run suburbs:build
//
// Suburb boundaries © Wellington City Council.

export interface GeneratedArea {
  id: string;
  /** Council's own spelling. The join key for signals.suburb — do not localise. */
  suburb: string;
  /** What a resident sees. Adds macrons Council's data leaves off. */
  label: string;
  region: string;
  /** [lng, lat] */
  centre: [number, number];
  radiusM: number;
  /** True where the centre was set by hand because the centroid misleads. */
  tuned: boolean;
  blurb: string | null;
}

/** In picker order: south coast first, then outward. */
export const GENERATED_AREAS: GeneratedArea[] = [
  {
    "id": "owhiro-bay",
    "suburb": "Owhiro Bay",
    "label": "Ōwhiro Bay",
    "region": "South coast",
    "centre": [
      174.7622,
      -41.3456
    ],
    "radiusM": 1200,
    "tuned": true,
    "blurb": "Ōwhiro Bay Parade, the quarry end, Te Kopahou."
  },
  {
    "id": "island-bay",
    "suburb": "Island Bay",
    "label": "Island Bay",
    "region": "South coast",
    "centre": [
      174.7756,
      -41.3399
    ],
    "radiusM": 1300,
    "tuned": true,
    "blurb": "The Parade, Shorland Park, the Esplanade."
  },
  {
    "id": "southgate",
    "suburb": "Southgate",
    "label": "Southgate",
    "region": "South coast",
    "centre": [
      174.78079,
      -41.33772
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": "The hill between Island Bay and Houghton Bay."
  },
  {
    "id": "houghton-bay",
    "suburb": "Houghton Bay",
    "label": "Houghton Bay",
    "region": "South coast",
    "centre": [
      174.7897,
      -41.34
    ],
    "radiusM": 1000,
    "tuned": true,
    "blurb": "Houghton Bay Road, Te Raekaihau Point."
  },
  {
    "id": "melrose",
    "suburb": "Melrose",
    "label": "Melrose",
    "region": "South coast",
    "centre": [
      174.78828,
      -41.32542
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": "The zoo, Melrose Park, Houghton Valley."
  },
  {
    "id": "lyall-bay",
    "suburb": "Lyall Bay",
    "label": "Lyall Bay",
    "region": "South coast",
    "centre": [
      174.7997,
      -41.3283
    ],
    "radiusM": 1400,
    "tuned": true,
    "blurb": "Lyall Parade, the surf club, Queens Drive."
  },
  {
    "id": "moa-point",
    "suburb": "Moa Point",
    "label": "Moa Point",
    "region": "South coast",
    "centre": [
      174.8118,
      -41.3417
    ],
    "radiusM": 1100,
    "tuned": true,
    "blurb": "Moa Point Road, the airport south end."
  },
  {
    "id": "breaker-bay",
    "suburb": "Breaker Bay",
    "label": "Breaker Bay",
    "region": "South coast",
    "centre": [
      174.82652,
      -41.33487
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": "Breaker Bay Road, the Pass of Branda."
  },
  {
    "id": "karaka-bays",
    "suburb": "Karaka Bays",
    "label": "Karaka Bays",
    "region": "South coast",
    "centre": [
      174.8307,
      -41.30264
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "seatoun",
    "suburb": "Seatoun",
    "label": "Seatoun",
    "region": "South coast",
    "centre": [
      174.8307,
      -41.32216
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": "Seatoun Wharf, Marine Parade, the tunnel."
  },
  {
    "id": "strathmore-park",
    "suburb": "Strathmore Park",
    "label": "Strathmore Park",
    "region": "South coast",
    "centre": [
      174.81937,
      -41.33217
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "miramar",
    "suburb": "Miramar",
    "label": "Miramar",
    "region": "Eastern suburbs",
    "centre": [
      174.81945,
      -41.31501
    ],
    "radiusM": 955,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "maupuia",
    "suburb": "Maupuia",
    "label": "Maupuia",
    "region": "Eastern suburbs",
    "centre": [
      174.82428,
      -41.29707
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "rongotai",
    "suburb": "Rongotai",
    "label": "Rongotai",
    "region": "Eastern suburbs",
    "centre": [
      174.80656,
      -41.32658
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "kilbirnie",
    "suburb": "Kilbirnie",
    "label": "Kilbirnie",
    "region": "Eastern suburbs",
    "centre": [
      174.79582,
      -41.3175
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "hataitai",
    "suburb": "Hataitai",
    "label": "Hataitai",
    "region": "Eastern suburbs",
    "centre": [
      174.79623,
      -41.30391
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "roseneath",
    "suburb": "Roseneath",
    "label": "Roseneath",
    "region": "Eastern suburbs",
    "centre": [
      174.80111,
      -41.2924
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "wellington-central",
    "suburb": "Wellington Central",
    "label": "Wellington Central",
    "region": "City and inner suburbs",
    "centre": [
      174.77611,
      -41.28487
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "te-aro",
    "suburb": "Te Aro",
    "label": "Te Aro",
    "region": "City and inner suburbs",
    "centre": [
      174.77706,
      -41.29337
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "pipitea",
    "suburb": "Pipitea",
    "label": "Pipitea",
    "region": "City and inner suburbs",
    "centre": [
      174.78427,
      -41.27362
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "thorndon",
    "suburb": "Thorndon",
    "label": "Thorndon",
    "region": "City and inner suburbs",
    "centre": [
      174.77422,
      -41.27246
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "mount-cook",
    "suburb": "Mount Cook",
    "label": "Mount Cook",
    "region": "City and inner suburbs",
    "centre": [
      174.77417,
      -41.30294
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "mount-victoria",
    "suburb": "Mount Victoria",
    "label": "Mount Victoria",
    "region": "City and inner suburbs",
    "centre": [
      174.78721,
      -41.29846
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "oriental-bay",
    "suburb": "Oriental Bay",
    "label": "Oriental Bay",
    "region": "City and inner suburbs",
    "centre": [
      174.794,
      -41.29155
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "aro-valley",
    "suburb": "Aro Valley",
    "label": "Aro Valley",
    "region": "City and inner suburbs",
    "centre": [
      174.76155,
      -41.29529
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "kelburn",
    "suburb": "Kelburn",
    "label": "Kelburn",
    "region": "City and inner suburbs",
    "centre": [
      174.7654,
      -41.28641
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "highbury",
    "suburb": "Highbury",
    "label": "Highbury",
    "region": "City and inner suburbs",
    "centre": [
      174.75383,
      -41.29579
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "newtown",
    "suburb": "Newtown",
    "label": "Newtown",
    "region": "Southern suburbs",
    "centre": [
      174.78183,
      -41.31328
    ],
    "radiusM": 820,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "berhampore",
    "suburb": "Berhampore",
    "label": "Berhampore",
    "region": "Southern suburbs",
    "centre": [
      174.77532,
      -41.32339
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "vogeltown",
    "suburb": "Vogeltown",
    "label": "Vogeltown",
    "region": "Southern suburbs",
    "centre": [
      174.76937,
      -41.3135
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "mornington",
    "suburb": "Mornington",
    "label": "Mornington",
    "region": "Southern suburbs",
    "centre": [
      174.76595,
      -41.31872
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "kingston",
    "suburb": "Kingston",
    "label": "Kingston",
    "region": "Southern suburbs",
    "centre": [
      174.76333,
      -41.32435
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "brooklyn",
    "suburb": "Brooklyn",
    "label": "Brooklyn",
    "region": "Southern suburbs",
    "centre": [
      174.72686,
      -41.32323
    ],
    "radiusM": 2147,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "karori",
    "suburb": "Karori",
    "label": "Karori",
    "region": "Western suburbs",
    "centre": [
      174.72984,
      -41.29278
    ],
    "radiusM": 2215,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "northland",
    "suburb": "Northland",
    "label": "Northland",
    "region": "Western suburbs",
    "centre": [
      174.76063,
      -41.27862
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "wilton",
    "suburb": "Wilton",
    "label": "Wilton",
    "region": "Western suburbs",
    "centre": [
      174.75506,
      -41.26683
    ],
    "radiusM": 894,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "wadestown",
    "suburb": "Wadestown",
    "label": "Wadestown",
    "region": "Western suburbs",
    "centre": [
      174.77555,
      -41.26229
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "makara",
    "suburb": "Makara",
    "label": "Makara",
    "region": "Western suburbs",
    "centre": [
      174.67875,
      -41.27908
    ],
    "radiusM": 4000,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "makara-beach",
    "suburb": "Makara Beach",
    "label": "Makara Beach",
    "region": "Western suburbs",
    "centre": [
      174.71312,
      -41.22165
    ],
    "radiusM": 1031,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "ohariu",
    "suburb": "Ohariu",
    "label": "Ohariu",
    "region": "Western suburbs",
    "centre": [
      174.76726,
      -41.19612
    ],
    "radiusM": 4000,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "ngaio",
    "suburb": "Ngaio",
    "label": "Ngaio",
    "region": "Onslow and the northern hills",
    "centre": [
      174.77191,
      -41.24895
    ],
    "radiusM": 1008,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "khandallah",
    "suburb": "Khandallah",
    "label": "Khandallah",
    "region": "Onslow and the northern hills",
    "centre": [
      174.79214,
      -41.24551
    ],
    "radiusM": 1192,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "crofton-downs",
    "suburb": "Crofton Downs",
    "label": "Crofton Downs",
    "region": "Onslow and the northern hills",
    "centre": [
      174.76024,
      -41.25623
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "kaiwharawhara",
    "suburb": "Kaiwharawhara",
    "label": "Kaiwharawhara",
    "region": "Onslow and the northern hills",
    "centre": [
      174.79144,
      -41.25753
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "ngauranga",
    "suburb": "Ngauranga",
    "label": "Ngauranga",
    "region": "Onslow and the northern hills",
    "centre": [
      174.81297,
      -41.24083
    ],
    "radiusM": 823,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "broadmeadows",
    "suburb": "Broadmeadows",
    "label": "Broadmeadows",
    "region": "Onslow and the northern hills",
    "centre": [
      174.79192,
      -41.2333
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "horokiwi",
    "suburb": "Horokiwi",
    "label": "Horokiwi",
    "region": "Onslow and the northern hills",
    "centre": [
      174.85209,
      -41.20677
    ],
    "radiusM": 1511,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "johnsonville",
    "suburb": "Johnsonville",
    "label": "Johnsonville",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.80088,
      -41.22383
    ],
    "radiusM": 1107,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "newlands",
    "suburb": "Newlands",
    "label": "Newlands",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.82531,
      -41.22861
    ],
    "radiusM": 1188,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "churton-park",
    "suburb": "Churton Park",
    "label": "Churton Park",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.8065,
      -41.20075
    ],
    "radiusM": 1122,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "glenside",
    "suburb": "Glenside",
    "label": "Glenside",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.81973,
      -41.19728
    ],
    "radiusM": 810,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "grenada-village",
    "suburb": "Grenada Village",
    "label": "Grenada Village",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.8299,
      -41.20183
    ],
    "radiusM": 876,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "grenada-north",
    "suburb": "Grenada North",
    "label": "Grenada North",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.84249,
      -41.18721
    ],
    "radiusM": 904,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "paparangi",
    "suburb": "Paparangi",
    "label": "Paparangi",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.81914,
      -41.21674
    ],
    "radiusM": 800,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "woodridge",
    "suburb": "Woodridge",
    "label": "Woodridge",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.83453,
      -41.21235
    ],
    "radiusM": 818,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "takapu-valley",
    "suburb": "Takapu Valley",
    "label": "Takapu Valley",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.86697,
      -41.16812
    ],
    "radiusM": 1808,
    "tuned": false,
    "blurb": null
  },
  {
    "id": "tawa",
    "suburb": "Tawa",
    "label": "Tawa",
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.82745,
      -41.17056
    ],
    "radiusM": 1797,
    "tuned": false,
    "blurb": null
  }
];

export const REGION_ORDER: string[] = ["South coast", "Eastern suburbs", "City and inner suburbs", "Southern suburbs", "Western suburbs", "Onslow and the northern hills", "Northern suburbs and Tawa"];
