// GENERATED by prototype-1/scripts/build_suburbs.py — do not edit by hand.
//
// The 57 Wellington City suburbs, from Council's own boundary polygons.
// `centre` is the polygon centroid and `radiusM` the radius of a circle of
// equal area, except for the five south coast bays, whose centres are hand-set
// because their boundaries run from the beach over the tops.
//
// Regenerate from the prototype-1 directory with:  bun run suburbs:build
//
// Suburb boundaries © Wellington City Council.

/** In picker order: south coast first, then outward. */
export const AREAS = [
  {
    "id": "owhiro-bay",
    "suburb": "Owhiro Bay",
    "label": "Ōwhiro Bay",
    "postcode": 6023,
    "region": "South coast",
    "centre": [
      174.7622,
      -41.3456
    ],
    "radiusM": 1200
  },
  {
    "id": "island-bay",
    "suburb": "Island Bay",
    "label": "Island Bay",
    "postcode": 6023,
    "region": "South coast",
    "centre": [
      174.7756,
      -41.3399
    ],
    "radiusM": 1300
  },
  {
    "id": "southgate",
    "suburb": "Southgate",
    "label": "Southgate",
    "postcode": 6023,
    "region": "South coast",
    "centre": [
      174.78079,
      -41.33772
    ],
    "radiusM": 800
  },
  {
    "id": "houghton-bay",
    "suburb": "Houghton Bay",
    "label": "Houghton Bay",
    "postcode": 6023,
    "region": "South coast",
    "centre": [
      174.7897,
      -41.34
    ],
    "radiusM": 1000
  },
  {
    "id": "melrose",
    "suburb": "Melrose",
    "label": "Melrose",
    "postcode": 6023,
    "region": "South coast",
    "centre": [
      174.78828,
      -41.32542
    ],
    "radiusM": 800
  },
  {
    "id": "lyall-bay",
    "suburb": "Lyall Bay",
    "label": "Lyall Bay",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.7997,
      -41.3283
    ],
    "radiusM": 1400
  },
  {
    "id": "moa-point",
    "suburb": "Moa Point",
    "label": "Moa Point",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.8118,
      -41.3417
    ],
    "radiusM": 1100
  },
  {
    "id": "breaker-bay",
    "suburb": "Breaker Bay",
    "label": "Breaker Bay",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.82652,
      -41.33487
    ],
    "radiusM": 800
  },
  {
    "id": "karaka-bays",
    "suburb": "Karaka Bays",
    "label": "Karaka Bays",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.8307,
      -41.30264
    ],
    "radiusM": 800
  },
  {
    "id": "seatoun",
    "suburb": "Seatoun",
    "label": "Seatoun",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.8307,
      -41.32216
    ],
    "radiusM": 800
  },
  {
    "id": "strathmore-park",
    "suburb": "Strathmore Park",
    "label": "Strathmore Park",
    "postcode": 6022,
    "region": "South coast",
    "centre": [
      174.81937,
      -41.33217
    ],
    "radiusM": 800
  },
  {
    "id": "miramar",
    "suburb": "Miramar",
    "label": "Miramar",
    "postcode": 6022,
    "region": "Eastern suburbs",
    "centre": [
      174.81945,
      -41.31501
    ],
    "radiusM": 955
  },
  {
    "id": "maupuia",
    "suburb": "Maupuia",
    "label": "Maupuia",
    "postcode": 6022,
    "region": "Eastern suburbs",
    "centre": [
      174.82428,
      -41.29707
    ],
    "radiusM": 800
  },
  {
    "id": "rongotai",
    "suburb": "Rongotai",
    "label": "Rongotai",
    "postcode": 6022,
    "region": "Eastern suburbs",
    "centre": [
      174.80656,
      -41.32658
    ],
    "radiusM": 800
  },
  {
    "id": "kilbirnie",
    "suburb": "Kilbirnie",
    "label": "Kilbirnie",
    "postcode": 6022,
    "region": "Eastern suburbs",
    "centre": [
      174.79582,
      -41.3175
    ],
    "radiusM": 800
  },
  {
    "id": "hataitai",
    "suburb": "Hataitai",
    "label": "Hataitai",
    "postcode": 6021,
    "region": "Eastern suburbs",
    "centre": [
      174.79623,
      -41.30391
    ],
    "radiusM": 800
  },
  {
    "id": "roseneath",
    "suburb": "Roseneath",
    "label": "Roseneath",
    "postcode": 6011,
    "region": "Eastern suburbs",
    "centre": [
      174.80111,
      -41.2924
    ],
    "radiusM": 800
  },
  {
    "id": "wellington-central",
    "suburb": "Wellington Central",
    "label": "Wellington Central",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.77611,
      -41.28487
    ],
    "radiusM": 800
  },
  {
    "id": "te-aro",
    "suburb": "Te Aro",
    "label": "Te Aro",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.77706,
      -41.29337
    ],
    "radiusM": 800
  },
  {
    "id": "pipitea",
    "suburb": "Pipitea",
    "label": "Pipitea",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.78427,
      -41.27362
    ],
    "radiusM": 800
  },
  {
    "id": "thorndon",
    "suburb": "Thorndon",
    "label": "Thorndon",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.77422,
      -41.27246
    ],
    "radiusM": 800
  },
  {
    "id": "mount-cook",
    "suburb": "Mount Cook",
    "label": "Mount Cook",
    "postcode": 6021,
    "region": "City and inner suburbs",
    "centre": [
      174.77417,
      -41.30294
    ],
    "radiusM": 800
  },
  {
    "id": "mount-victoria",
    "suburb": "Mount Victoria",
    "label": "Mount Victoria",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.78721,
      -41.29846
    ],
    "radiusM": 800
  },
  {
    "id": "oriental-bay",
    "suburb": "Oriental Bay",
    "label": "Oriental Bay",
    "postcode": 6011,
    "region": "City and inner suburbs",
    "centre": [
      174.794,
      -41.29155
    ],
    "radiusM": 800
  },
  {
    "id": "aro-valley",
    "suburb": "Aro Valley",
    "label": "Aro Valley",
    "postcode": 6021,
    "region": "City and inner suburbs",
    "centre": [
      174.76155,
      -41.29529
    ],
    "radiusM": 800
  },
  {
    "id": "kelburn",
    "suburb": "Kelburn",
    "label": "Kelburn",
    "postcode": 6012,
    "region": "City and inner suburbs",
    "centre": [
      174.7654,
      -41.28641
    ],
    "radiusM": 800
  },
  {
    "id": "highbury",
    "suburb": "Highbury",
    "label": "Highbury",
    "postcode": 6012,
    "region": "City and inner suburbs",
    "centre": [
      174.75383,
      -41.29579
    ],
    "radiusM": 800
  },
  {
    "id": "newtown",
    "suburb": "Newtown",
    "label": "Newtown",
    "postcode": 6021,
    "region": "Southern suburbs",
    "centre": [
      174.78183,
      -41.31328
    ],
    "radiusM": 820
  },
  {
    "id": "berhampore",
    "suburb": "Berhampore",
    "label": "Berhampore",
    "postcode": 6023,
    "region": "Southern suburbs",
    "centre": [
      174.77532,
      -41.32339
    ],
    "radiusM": 800
  },
  {
    "id": "vogeltown",
    "suburb": "Vogeltown",
    "label": "Vogeltown",
    "postcode": 6021,
    "region": "Southern suburbs",
    "centre": [
      174.76937,
      -41.3135
    ],
    "radiusM": 800
  },
  {
    "id": "mornington",
    "suburb": "Mornington",
    "label": "Mornington",
    "postcode": 6021,
    "region": "Southern suburbs",
    "centre": [
      174.76595,
      -41.31872
    ],
    "radiusM": 800
  },
  {
    "id": "kingston",
    "suburb": "Kingston",
    "label": "Kingston",
    "postcode": 6021,
    "region": "Southern suburbs",
    "centre": [
      174.76333,
      -41.32435
    ],
    "radiusM": 800
  },
  {
    "id": "brooklyn",
    "suburb": "Brooklyn",
    "label": "Brooklyn",
    "postcode": 6021,
    "region": "Southern suburbs",
    "centre": [
      174.72686,
      -41.32323
    ],
    "radiusM": 2147
  },
  {
    "id": "karori",
    "suburb": "Karori",
    "label": "Karori",
    "postcode": 6012,
    "region": "Western suburbs",
    "centre": [
      174.72984,
      -41.29278
    ],
    "radiusM": 2215
  },
  {
    "id": "northland",
    "suburb": "Northland",
    "label": "Northland",
    "postcode": 6012,
    "region": "Western suburbs",
    "centre": [
      174.76063,
      -41.27862
    ],
    "radiusM": 800
  },
  {
    "id": "wilton",
    "suburb": "Wilton",
    "label": "Wilton",
    "postcode": 6012,
    "region": "Western suburbs",
    "centre": [
      174.75506,
      -41.26683
    ],
    "radiusM": 894
  },
  {
    "id": "wadestown",
    "suburb": "Wadestown",
    "label": "Wadestown",
    "postcode": 6012,
    "region": "Western suburbs",
    "centre": [
      174.77555,
      -41.26229
    ],
    "radiusM": 800
  },
  {
    "id": "makara",
    "suburb": "Makara",
    "label": "Makara",
    "postcode": 6972,
    "region": "Western suburbs",
    "centre": [
      174.67875,
      -41.27908
    ],
    "radiusM": 4000
  },
  {
    "id": "makara-beach",
    "suburb": "Makara Beach",
    "label": "Makara Beach",
    "postcode": 6972,
    "region": "Western suburbs",
    "centre": [
      174.71312,
      -41.22165
    ],
    "radiusM": 1031
  },
  {
    "id": "ohariu",
    "suburb": "Ohariu",
    "label": "Ohariu",
    "postcode": 6037,
    "region": "Western suburbs",
    "centre": [
      174.76726,
      -41.19612
    ],
    "radiusM": 4000
  },
  {
    "id": "ngaio",
    "suburb": "Ngaio",
    "label": "Ngaio",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.77191,
      -41.24895
    ],
    "radiusM": 1008
  },
  {
    "id": "khandallah",
    "suburb": "Khandallah",
    "label": "Khandallah",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.79214,
      -41.24551
    ],
    "radiusM": 1192
  },
  {
    "id": "crofton-downs",
    "suburb": "Crofton Downs",
    "label": "Crofton Downs",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.76024,
      -41.25623
    ],
    "radiusM": 800
  },
  {
    "id": "kaiwharawhara",
    "suburb": "Kaiwharawhara",
    "label": "Kaiwharawhara",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.79144,
      -41.25753
    ],
    "radiusM": 800
  },
  {
    "id": "ngauranga",
    "suburb": "Ngauranga",
    "label": "Ngauranga",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.81297,
      -41.24083
    ],
    "radiusM": 823
  },
  {
    "id": "broadmeadows",
    "suburb": "Broadmeadows",
    "label": "Broadmeadows",
    "postcode": 6035,
    "region": "Onslow and the northern hills",
    "centre": [
      174.79192,
      -41.2333
    ],
    "radiusM": 800
  },
  {
    "id": "horokiwi",
    "suburb": "Horokiwi",
    "label": "Horokiwi",
    "postcode": 5016,
    "region": "Onslow and the northern hills",
    "centre": [
      174.85209,
      -41.20677
    ],
    "radiusM": 1511
  },
  {
    "id": "johnsonville",
    "suburb": "Johnsonville",
    "label": "Johnsonville",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.80088,
      -41.22383
    ],
    "radiusM": 1107
  },
  {
    "id": "newlands",
    "suburb": "Newlands",
    "label": "Newlands",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.82531,
      -41.22861
    ],
    "radiusM": 1188
  },
  {
    "id": "churton-park",
    "suburb": "Churton Park",
    "label": "Churton Park",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.8065,
      -41.20075
    ],
    "radiusM": 1122
  },
  {
    "id": "glenside",
    "suburb": "Glenside",
    "label": "Glenside",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.81973,
      -41.19728
    ],
    "radiusM": 810
  },
  {
    "id": "grenada-village",
    "suburb": "Grenada Village",
    "label": "Grenada Village",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.8299,
      -41.20183
    ],
    "radiusM": 876
  },
  {
    "id": "grenada-north",
    "suburb": "Grenada North",
    "label": "Grenada North",
    "postcode": 5028,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.84249,
      -41.18721
    ],
    "radiusM": 904
  },
  {
    "id": "paparangi",
    "suburb": "Paparangi",
    "label": "Paparangi",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.81914,
      -41.21674
    ],
    "radiusM": 800
  },
  {
    "id": "woodridge",
    "suburb": "Woodridge",
    "label": "Woodridge",
    "postcode": 6037,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.83453,
      -41.21235
    ],
    "radiusM": 818
  },
  {
    "id": "takapu-valley",
    "suburb": "Takapu Valley",
    "label": "Takapu Valley",
    "postcode": 5028,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.86697,
      -41.16812
    ],
    "radiusM": 1808
  },
  {
    "id": "tawa",
    "suburb": "Tawa",
    "label": "Tawa",
    "postcode": 5028,
    "region": "Northern suburbs and Tawa",
    "centre": [
      174.82745,
      -41.17056
    ],
    "radiusM": 1797
  }
]

export const REGION_ORDER = ["South coast", "Eastern suburbs", "City and inner suburbs", "Southern suburbs", "Western suburbs", "Onslow and the northern hills", "Northern suburbs and Tawa"]

export const AREAS_BY_ID = Object.fromEntries(AREAS.map(a => [a.id, a]))

export const AREA_GROUPS = REGION_ORDER.map(region => ({
  region,
  areas: AREAS.filter(a => a.region === region),
}))
