-- Derive a community report's suburb in the database, from its own coordinate.
--
-- Why this is not done in the client
-- ---------------------------------
-- A public submitter may state a suburb no more than they may state a status.
-- The whole reason `community_reports` has a column-level INSERT grant is that
-- a report must not be able to be born as anything it has not earned. Letting
-- the browser post `suburb` alongside `lng`/`lat` would reopen exactly that
-- hole from a different direction: a report could place itself in Island Bay
-- while sitting in Tawa, and the corroboration counter and every "reports near
-- you" filter downstream would believe it.
--
-- So the suburb is computed here, from the point that is already constrained by
-- the bbox CHECK, by a trigger the submitter cannot address. `suburb` and
-- `suburb_exact` stay out of the anon INSERT grant, which means an attempt to
-- set them is rejected by Postgres before this function ever runs.
--
-- Signals take a different route on purpose: they are stamped in the ingest
-- function under service_role, where the data has already been fetched from an
-- attributable publisher and there is no untrusted submitter in the path.
-- Both routes read boundaries generated by the same script from the same fetch,
-- so they cannot disagree about where a boundary is.

CREATE TABLE public.suburb_boundaries (
  name     text PRIMARY KEY,
  postcode integer NOT NULL,
  min_lng  double precision NOT NULL,
  min_lat  double precision NOT NULL,
  max_lng  double precision NOT NULL,
  max_lat  double precision NOT NULL
);

-- One row per outer ring. Parallel float arrays rather than jsonb because the
-- lookup walks them element by element and array subscripting is far cheaper
-- than jsonb path extraction.
CREATE TABLE public.suburb_rings (
  name    text NOT NULL REFERENCES public.suburb_boundaries(name) ON DELETE CASCADE,
  ring_no integer NOT NULL,
  lngs    double precision[] NOT NULL,
  lats    double precision[] NOT NULL,
  PRIMARY KEY (name, ring_no)
);

ALTER TABLE public.suburb_boundaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suburb_rings      ENABLE ROW LEVEL SECURITY;

-- Public reference data. Readable by anyone, writable by no one but the seed.
CREATE POLICY "anon reads suburb boundaries"
  ON public.suburb_boundaries FOR SELECT TO anon USING (TRUE);
CREATE POLICY "anon reads suburb rings"
  ON public.suburb_rings FOR SELECT TO anon USING (TRUE);

GRANT SELECT ON public.suburb_boundaries, public.suburb_rings TO anon;
GRANT ALL    ON public.suburb_boundaries, public.suburb_rings TO service_role;

COMMENT ON TABLE public.suburb_boundaries IS
  'WCC suburb polygons. Generated by scripts/build_suburbs.py — do not edit rows by hand.';


-- Metres per degree at 41.3 S. Longitude degrees are shorter this far south:
-- cos(41.3 deg) ~ 0.7513. Good to a fraction of a percent over a city.
CREATE FUNCTION public.suburb_m_per_deg_lat() RETURNS double precision
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT 111320.0 $$;
CREATE FUNCTION public.suburb_m_per_deg_lng() RETURNS double precision
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT 111320.0 * 0.7513 $$;


-- Ray casting. Mirrors inRing() in src/lib/suburbs.ts, deliberately line for
-- line, so the two implementations can be compared when one of them is wrong.
CREATE FUNCTION public.suburb_point_in_ring(
  p_lng double precision,
  p_lat double precision,
  p_lngs double precision[],
  p_lats double precision[]
) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
  n      integer := array_length(p_lngs, 1);
  inside boolean := FALSE;
  i      integer;
  j      integer;
  xi     double precision;
  yi     double precision;
  xj     double precision;
  yj     double precision;
  x      double precision;
BEGIN
  IF n IS NULL OR n < 4 THEN RETURN FALSE; END IF;

  j := n;
  FOR i IN 1..n LOOP
    xi := p_lngs[i]; yi := p_lats[i];
    xj := p_lngs[j]; yj := p_lats[j];
    -- Count an edge only when the ray passes between its endpoints.
    IF (yi > p_lat) <> (yj > p_lat) THEN
      x := (xj - xi) * (p_lat - yi) / (yj - yi) + xi;
      IF p_lng < x THEN inside := NOT inside; END IF;
    END IF;
    j := i;
  END LOOP;

  RETURN inside;
END;
$$;


-- Metres from a point to a ring, in the local flat approximation.
CREATE FUNCTION public.suburb_dist_to_ring(
  p_lng double precision,
  p_lat double precision,
  p_lngs double precision[],
  p_lats double precision[]
) RETURNS double precision
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
  n     integer := array_length(p_lngs, 1);
  best  double precision := 1e18;
  i     integer;
  mlng  double precision := public.suburb_m_per_deg_lng();
  mlat  double precision := public.suburb_m_per_deg_lat();
  px    double precision; py double precision;
  vx    double precision; vy double precision;
  len2  double precision; t double precision;
  dx    double precision; dy double precision; d double precision;
BEGIN
  IF n IS NULL OR n < 2 THEN RETURN best; END IF;

  FOR i IN 1..(n - 1) LOOP
    px := (p_lng - p_lngs[i]) * mlng;
    py := (p_lat - p_lats[i]) * mlat;
    vx := (p_lngs[i + 1] - p_lngs[i]) * mlng;
    vy := (p_lats[i + 1] - p_lats[i]) * mlat;

    len2 := vx * vx + vy * vy;
    IF len2 = 0 THEN
      t := 0;
    ELSE
      t := greatest(0, least(1, (px * vx + py * vy) / len2));
    END IF;

    dx := px - t * vx;
    dy := py - t * vy;
    d  := sqrt(dx * dx + dy * dy);
    IF d < best THEN best := d; END IF;
  END LOOP;

  RETURN best;
END;
$$;


-- The suburb containing this point, or the nearest within 3 km.
--
-- `exact` FALSE means the point is outside every boundary — a report from the
-- sea wall, a gauge in the water. Callers must word those "off X", never "in
-- X". Returns no row beyond 3 km, which is the right answer for Cook Strait.
CREATE FUNCTION public.suburb_for(
  p_lng double precision,
  p_lat double precision
) RETURNS TABLE (suburb text, exact boolean)
LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
  limit_m  constant double precision := 3000;
  pad_lng  double precision := limit_m / public.suburb_m_per_deg_lng();
  pad_lat  double precision := limit_m / public.suburb_m_per_deg_lat();
BEGIN
  IF p_lng IS NULL OR p_lat IS NULL THEN RETURN; END IF;

  -- Inside a boundary. The bbox test rejects 56 of 57 suburbs before any ring
  -- is walked.
  RETURN QUERY
    SELECT b.name, TRUE
      FROM public.suburb_boundaries b
      JOIN public.suburb_rings r ON r.name = b.name
     WHERE p_lng BETWEEN b.min_lng AND b.max_lng
       AND p_lat BETWEEN b.min_lat AND b.max_lat
       AND public.suburb_point_in_ring(p_lng, p_lat, r.lngs, r.lats)
     LIMIT 1;

  IF FOUND THEN RETURN; END IF;

  -- Otherwise the nearest boundary within 3 km.
  RETURN QUERY
    SELECT d.name, FALSE
      FROM (
        SELECT b.name,
               min(public.suburb_dist_to_ring(p_lng, p_lat, r.lngs, r.lats)) AS m
          FROM public.suburb_boundaries b
          JOIN public.suburb_rings r ON r.name = b.name
         WHERE p_lng BETWEEN b.min_lng - pad_lng AND b.max_lng + pad_lng
           AND p_lat BETWEEN b.min_lat - pad_lat AND b.max_lat + pad_lat
         GROUP BY b.name
      ) d
     WHERE d.m <= limit_m
     ORDER BY d.m
     LIMIT 1;
END;
$$;


-- Stamp the suburb on every community report, from its own point.
--
-- BEFORE INSERT OR UPDATE, and it overwrites unconditionally: whatever arrives
-- in these columns is discarded and replaced with the derived value. The anon
-- grant already makes it impossible to submit them, so this is the second of
-- two locks rather than the only one.
CREATE FUNCTION public.community_reports_set_suburb()
RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  m record;
BEGIN
  NEW.suburb := NULL;
  NEW.suburb_exact := NULL;

  IF NEW.lng IS NOT NULL AND NEW.lat IS NOT NULL THEN
    SELECT * INTO m FROM public.suburb_for(NEW.lng, NEW.lat);
    IF FOUND THEN
      NEW.suburb := m.suburb;
      NEW.suburb_exact := m.exact;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER community_reports_suburb
  BEFORE INSERT OR UPDATE OF lng, lat ON public.community_reports
  FOR EACH ROW EXECUTE FUNCTION public.community_reports_set_suburb();

COMMENT ON FUNCTION public.community_reports_set_suburb() IS
  'Derives suburb from the submitted point. A report can never state its own suburb.';
