-- Source registry: who published each item, under what licence, and whether the
-- feed is currently healthy.
--
-- This table does double duty. It supplies per-item provenance (every signal
-- joins back to it for publisher, licence and attribution), AND it drives the
-- source health strip in the UI. The brief says "show reliability, don't hide
-- it" — a feed that is failing has to be visible as failing, not silently
-- absent. `last_status` is what makes that possible.
--
-- Rows are GENERATED by scripts/build_sources.py from the WCC catalogue and
-- applied by supabase/seed.sql. Do not hand-edit source rows.

CREATE TABLE public.sources (
  id                text PRIMARY KEY,
  name              text NOT NULL,
  publisher         text NOT NULL,

  -- Who is speaking. Drives the visual tier and the relevance floor.
  tier              text NOT NULL
                      CHECK (tier IN ('official','council','measured','community','context')),

  -- How things from this source are known, by default. Individual signals may
  -- override. Kept separate from `tier` on purpose: tier answers "who said it",
  -- evidence answers "how do they know". A council road closure is observed; an
  -- Open-Meteo figure is forecast; a flood layer is modelled.
  evidence_default  text NOT NULL
                      CHECK (evidence_default IN ('observed','measured','modelled','forecast','reported')),

  layer_kind        text NOT NULL DEFAULT 'signal'
                      CHECK (layer_kind IN ('signal','feature_overlay','raster_overlay')),

  endpoint          text,
  -- MapLibre raster template carrying a {bbox-epsg-3857} placeholder.
  tile_url          text,
  -- ArcGIS sublayer index. Lives in `layers=show:N`, a query param, not the path.
  layer_index       integer,

  -- Grouping key for the polite per-host request queue in the ingest function.
  host              text,
  -- Measured, not assumed. Only NZTA and the EMA RSS need a server-side fetch.
  cors              text NOT NULL DEFAULT 'open'
                      CHECK (cors IN ('open','proxy_required')),

  licence           text,
  attribution       text NOT NULL,
  homepage          text,
  -- Traces back to an id in vendor/wcc-gis/catalogue.json where applicable.
  catalogue_id      text,

  refresh_seconds   integer NOT NULL DEFAULT 300,
  display_order     smallint NOT NULL DEFAULT 100,

  -- Health, written by every ingest run whether it succeeded or not.
  last_attempt_at   timestamptz,
  last_success_at   timestamptz,
  last_status       text NOT NULL DEFAULT 'never'
                      CHECK (last_status IN ('ok','error','stale','never')),
  last_error        text,
  last_item_count   integer,

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sources_tier_order ON public.sources (tier, display_order);

-- Shared updated_at trigger, used by every table in this schema.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER sources_set_updated_at
  BEFORE UPDATE ON public.sources
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS plus explicit GRANTs. Recent Supabase defaults do not auto-expose tables,
-- so enabling RLS on its own leaves the table unreadable; the GRANT is required
-- as well. anon reads, and only reads.
ALTER TABLE public.sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon reads sources"
  ON public.sources FOR SELECT TO anon USING (TRUE);

GRANT SELECT ON public.sources TO anon;
GRANT ALL    ON public.sources TO service_role;

COMMENT ON TABLE public.sources IS
  'Provenance and health registry. Generated from the WCC Emergency GIS catalogue by scripts/build_sources.py.';
